# Travis script for test-building this library.
language: c
dist: trusty
sudo: false

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
  - tar xf arduino-1.8.5-linux64.tar.xz
  - mv arduino-1.8.5 $HOME/arduino_ide
  - ln -s $PWD $HOME/arduino_ide/libraries/Test_Library
  - export PATH="$HOME/arduino_ide:$PATH"
  # keep args for these aligned for any common options. first is board name, second is region.
  - "function _samdopts { echo mcci:samd:${1:-mcci_catena_4450}:lorawan_region=${2:-us915} ; }"
  - "function _stm32l0opts { echo mcci:stm32:pnum=${1:-CATENA_4551}:opt=${3:-osstd}:xserial=${4:-generic}:usb=${5:-none}:upload_method=${6:-STLink} ; }"
  - function _projcfg { printf '#define COMPILE_REGRESSION_TEST 1\n#define CFG_%s 1\n#define CFG_sx1276_radio 1\n' ${1:-us915} ${2:-sx1276} > $PWD/project_config/lmic_project_config.h  ; }
  - 'function _expect_failure { if [ $? -eq 0 ]; then echo "Suceeded, but should have failed!" ; return 1 ; else echo "Failed, as expected"; return 0 ; fi ; }'
  - arduino --pref "boardsmanager.additional.urls=https://github.com/mcci-catena/arduino-boards/raw/master/BoardManagerFiles/package_mcci_index.json" --save-prefs

install:
 - arduino --install-boards mcci:samd
# - arduino --install-boards mcci:stm32

script:
 - "echo $(_stm32l0opts) $(_stm32l0opts '' projcfg)"
 - "echo $(_samdopts) $(_samdopts '' projcfg)"
 - arduino --verify --board $(_samdopts '' us915) $PWD/examples/raw-feather/raw-feather.ino
 - _projcfg us915 sx1276 && arduino --verify --board mcci:samd:mcci_catena_4450:lorawan_region=projcfg $PWD/examples/ttn-otaa-feather-us915/ttn-otaa-feather-us915.ino
 - _projcfg us915 sx1272 && arduino --verify --board mcci:samd:mcci_catena_4450:lorawan_region=projcfg $PWD/examples/ttn-otaa-feather-us915/ttn-otaa-feather-us915.ino
 - _projcfg us915 sx1234 && if arduino --verify --board mcci:samd:mcci_catena_4450:lorawan_region=projcfg $PWD/examples/ttn-otaa-feather-us915/ttn-otaa-feather-us915.ino ; then echo "should have failed!" ; false ; else echo "error (as expected) - passed" ; fi
 - _projcfg us915 sx1234 && { arduino --verify --board mcci:samd:mcci_catena_4450:lorawan_region=projcfg $PWD/examples/ttn-otaa-feather-us915/ttn-otaa-feather-us915.ino ; _expect_failure ; }
# - arduino --pref "build.verbose=true" --verify --board $(_stm32l0opts) $PWD/examples/raw-feather/raw-feather.ino
